### ISSUE TITLE
Allow overriding base defaultProps in extended structs

### ISSUE THREAD

**Issue by tehnomaag** [gcanti/tcomb#257]
### Version

3.2.14

### Expected behaviour

When extending an existing struct with some defaultProps set, the extended struct should be able to override base type's defaultProps values.

### Actual behaviour

A `mixin` call within `extendStruct` will throw an exception.

### Steps to reproduce

```
var BasePanelConfig = t.struct(
    { collapsed: t.Boolean, helpKey: t.maybe(t.String) },
    { defaultProps: { collapsed: false } }
);
var MyPanelConfig = BasePanelConfig.extend(
    { myThing: t.maybe(t.String) },
    { defaultProps: { collapsed: true, helpKey: "my-help-key" } }
)
```

### Stack trace and console log

```
> process.version  // node ver
'v6.6.0
> var t = require("tcomb")
> BasePanelConfig = t.struct({ collapsed: t.Boolean, helpKey: t.maybe(t.String) }, { defaultProps: { collapsed: false } } )
{ [Function: Struct]
  meta:
   { kind: 'struct',
     props: { collapsed: [Object], helpKey: [Object] },
     name: undefined,
     identity: false,
     strict: false,
     defaultProps: { collapsed: false } },
  displayName: 'Struct{collapsed: Boolean, helpKey: ?String}',
  is: [Function],
  update: [Function],
  extend: [Function] }
> MyPanelConfig = BasePanelConfig.extend({ myThing: t.maybe(t.String) }, { defaultProps: { collapsed: true, helpKey: "my-help-key" } })
TypeError: [tcomb] Invalid call to mixin(target, source, [overwrite]): cannot overwrite property "collapsed" of target object
    at Function.fail (./node_modules/tcomb/lib/fail.js:2:9)
    at assert (./node_modules/tcomb/lib/assert.js:14:12)
    at mixin (./node_modules/tcomb/lib/mixin.js:11:11)
    at extend (./node_modules/tcomb/lib/extend.js:50:3)
    at extendStruct (./node_modules/tcomb/lib/struct.js:19:10)
    at Function.Struct.extend (./node_modules/tcomb/lib/struct.js:112:12)
    at repl:1:33
    at sigintHandlersWrap (vm.js:22:35)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInThisContext (vm.js:21:12)
```

**Comment by gcanti** [comment]
Agreed. Would you like to send a PR?

**Comment by tehnomaag** [comment]
Sure, since I had a need for it just now, might as well help out :)
