### ISSUE TITLE
TComb crashed by validating against DOM in node

### ISSUE THREAD

**Issue by lwchkg** [gcanti/tcomb#286]
### Version

3.2.21

### Expected behaviour

Test should not crash on validating against "undefined" type. (Actually Element here).

### Actual behaviour

See below

### Steps to reproduce

1.   `git clone https://github.com/lwchkg/sunlight-x.git`
2.   `cd sunlight-x`
3.   `git checkout tcomb-bug`
4.   `yarn`
5.   `yarn test`. Should produce the stack traces similar to the following:

> ```
>  FAIL  test\diff.js
>   ● Test suite failed to run
> 
>     TypeError: [tcomb] Invalid argument type undefined supplied to maybe(type, [name]) combinator (expected a type)
> 
>       at Function.fail (node_modules/tcomb/lib/fail.js:2:9)
>       at assert (node_modules/tcomb/lib/assert.js:14:12)
>       at Function.maybe (node_modules/tcomb/lib/maybe.js:24:5)
>       at Object.<anonymous> (src/events.js:16:36)
>       at Object.<anonymous> (src/parser-context.js:156:204)
>       at Object.<anonymous> (src/languages.js:226:309)
>       at Object.<anonymous> (src/util.js:94:40)
>       at Object.<anonymous> (src/continuation.js:2:13)
>       at Object.<anonymous> (src/analyzer-context.js:7:21)
>       at Object.<anonymous> (src/analyzer.js:4:24)
>       at Object.<anonymous> (src/default-helpers.js:67:134)
>       at Object.<anonymous> (src/sunlight.js:1:337)
>       at Object.<anonymous> (test/fixtures/testsupport.js:11:17)
>       at Object.<anonymous> (test/diff.js:7:20)
>       at handle (node_modules/worker-farm/lib/child/index.js:44:8)
>       at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
>       at emitTwo (events.js:125:13)
>       at process.emit (events.js:213:7)
>       at handleMessage (internal/child_process.js:753:14)
>       at Pipe.channel.onread (internal/child_process.js:472:11)
> ```
> 

6.  `yarn run compile-debug`
7.  `node babel-out/events.js`. Should produce the following stacktrace.

> ```
>   node: Element
>         ^
> 
> ReferenceError: Element is not defined
>     at Object.<anonymous> (D:\Documents\pCloud Sync\github\sunlight-x\babel-out\events.js:28:9)
>     at Module._compile (module.js:569:30)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:575:3
> ```
> 

### Note

Sorry for not having the time to produce the minimal example. Anyway, here is the excerpt of `babel-out/events.js` causing the crash:
```js
var BeforeHighlightNodeEventArgs = exports.BeforeHighlightNodeEventArgs = _tcomb2.default.interface({
  node: Element
}, "BeforeHighlightNodeEventArgs");
```

Note: The type `Element` exists only in the browser, not node. Flow validate the type `Element` with internal libdefs.

**Comment by gcanti** [comment]
I guess is a babel-plugin-tcomb issue. You could try to add `Element` to [globals](https://github.com/gcanti/babel-plugin-tcomb#globals-arrayobject) 

```
"plugins": [
  ["tcomb", {
    "globals": {
      "Element": true
    }
  }]
]
```

**Comment by lwchkg** [comment]
Thanks. Added those things, and the babel compiled source seems normal now.
Unfortunately Jest still fails. So another round of node run.

Summary: I don't know why require `sunlight.js` failed, but require `sunlight.js` after `events.js` passed.

```
lwchkg@I7-4790 D:\Documents\pCloud Sync\github\sunlight-x                                                  
> node                                                                                                     
> sunlight = require("./babel-out/sunlight.js");                                                           
TypeError: [tcomb] Invalid argument type undefined supplied to maybe(type, [name]) combinator (expected a t
ype)                                                                                                       
    at Function.fail (D:\Documents\pCloud Sync\github\sunlight-x\node_modules\tcomb\lib\fail.js:2:9)       
    at assert (D:\Documents\pCloud Sync\github\sunlight-x\node_modules\tcomb\lib\assert.js:14:12)          
    at Function.maybe (D:\Documents\pCloud Sync\github\sunlight-x\node_modules\tcomb\lib\maybe.js:24:5)    
    at Object.<anonymous> (D:\Documents\pCloud Sync\github\sunlight-x\babel-out\events.js:34:36)           
    at Module._compile (module.js:569:30)                                                                  
    at Object.Module._extensions..js (module.js:580:10)                                                    
    at Module.load (module.js:503:32)                                                                      
    at tryModuleLoad (module.js:466:12)                                                                    
    at Function.Module._load (module.js:458:3)                                                             
    at Module.require (module.js:513:17)                                                                   
> events = require("./babel-out/events.js");                                                               
{ BeforeHighlightNodeEventArgs:                                                                            
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'BeforeHighlightNodeEventArgs',                                                              
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'BeforeHighlightNodeEventArgs',                                                          
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  BeforeHighlightEventArgs:                                                                                
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'BeforeHighlightEventArgs',                                                                  
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'BeforeHighlightEventArgs',                                                              
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  BeforeTokenizeEventArgs:                                                                                 
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'BeforeTokenizeEventArgs',                                                                   
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'BeforeTokenizeEventArgs',                                                               
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  AfterTokenizeEventArgs:                                                                                  
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'AfterTokenizeEventArgs',                                                                    
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'AfterTokenizeEventArgs',                                                                
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  BeforeAnalyzeEventArgs:                                                                                  
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'BeforeAnalyzeEventArgs',                                                                    
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'BeforeAnalyzeEventArgs',                                                                
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  AfterAnalyzeEventArgs:                                                                                   
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'AfterAnalyzeEventArgs',                                                                     
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'AfterAnalyzeEventArgs',                                                                 
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  AfterHighlightEventArgs:                                                                                 
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'AfterHighlightEventArgs',                                                                   
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'AfterHighlightEventArgs',                                                               
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  AfterHighlightNodeEventArgs:                                                                             
   { [Function: Interface]                                                                                 
     meta:                                                                                                 
      { kind: 'interface',                                                                                 
        props: [Object],                                                                                   
        name: 'AfterHighlightNodeEventArgs',                                                               
        identity: true,                                                                                    
        strict: false },                                                                                   
     displayName: 'AfterHighlightNodeEventArgs',                                                           
     is: [Function],                                                                                       
     update: [Function],                                                                                   
     extend: [Function] },                                                                                 
  BeforeHighlightNodeEvent: EventClass { delegates: [] },                                                  
  BeforeHighlightEvent: EventClass { delegates: [] },                                                      
  BeforeTokenizeEvent: EventClass { delegates: [] },                                                       
  AfterTokenizeEvent: EventClass { delegates: [] },                                                        
  BeforeAnalyzeEvent: EventClass { delegates: [] },                                                        
  AfterAnalyzeEvent: EventClass { delegates: [] },                                                         
  AfterHighlightEvent: EventClass { delegates: [] },                                                       
  AfterHighlightNodeEvent: EventClass { delegates: [] } }                                                  
> sunlight = require("./babel-out/sunlight.js");                                                           
{ version: '1.22.0',                                                                                       
  defaultAnalyzer: [Getter],                                                                               
  globalOptions: [Getter],                                                                                 
  registerLanguage: [Getter],                                                                              
  isRegistered: [Getter],                                                                                  
  Highlighter: [Function: Highlighter],                                                                    
  highlightAll: [Function: highlightAll] }                                                                 
>
```

**Comment by gcanti** [comment]
> sunlight = require("./babel-out/sunlight.js");                                                           
TypeError: [tcomb] Invalid argument type undefined supplied to maybe(type, [name]) combinator (expected a t
ype) 

I can't repro

```
# after yarn test
$ node
> sunlight = require("./babel-out/sunlight.js");      
{ version: '1.22.0',
  defaultAnalyzer: [Getter],
  globalOptions: [Getter],
  registerLanguage: [Getter],
  isRegistered: [Getter],
  Highlighter: [Function: Highlighter],
  highlightAll: [Function: highlightAll] }
> 
```

Could you update the branch? Also, let's move this discussion on your repo, this doesn't seem an issue related to tcomb

**Comment by lwchkg** [comment]
I found out the cause of the crash now: circular dependence of source code. i.e. Module "A" requires module "B", and module "B" also requires module "A".

This was okay with my code before adding babel-plugin-tcomb. But after adding babel-plugin-tcomb `events.js` (module B) require some code, rather than just to "import type", of code in `analyzer-context.js` (module A). (And of course, the exports of module A is not ready yet.)

So it appears to be an issue of babel-plugin-tcomb. I'll try to make a minimal example for this.

**Comment by lwchkg** [comment]
Added issue https://github.com/gcanti/babel-plugin-tcomb/issues/171. I think discussion should go there.
