### ISSUE TITLE
fromJSON t.maybe(t.Date) fails

### ISSUE THREAD

**Issue by rkmax** [gcanti/tcomb#310]
### Version

3.2.24

### Expected behaviour

It should turn the formatted date into a Date Object

### Actual behaviour

    "message": "Invalid value "2018-02-16T18:04:05.284Z" supplied to WorkSheet/viewedAt: ?Date"

### Steps to reproduce
```
// date.test.js
const t = require('tcomb');

const Sample = t.struct({
  date: t.maybe(t.Date)
});

const sample = Sample({date: new Date()});
const json = JSON.parse(JSON.stringify(sample));

const reSample = Sample(json);
```

### Stack trace and console log

```
node date.test.js
/home/rkmax/my_project/node_modules/tcomb/lib/fail.js:2
  throw new TypeError('[tcomb] ' + message);
  ^

TypeError: [tcomb] Invalid value "2018-02-21T18:01:31.721Z" supplied to Struct{date: ?Date}/date: ?Date
    at Function.fail (/home/rkmax/my_project/node_modules/tcomb/lib/fail.js:2:9)
    at assert (/home/rkmax/my_project/node_modules/tcomb/lib/assert.js:14:12)
    at Irreducible (/home/rkmax/my_project/node_modules/tcomb/lib/irreducible.js:18:7)
    at create (/home/rkmax/my_project/node_modules/tcomb/lib/create.js:9:104)
    at Maybe (/home/rkmax/my_project/node_modules/tcomb/lib/maybe.js:37:36)
    at create (/home/rkmax/my_project/node_modules/tcomb/lib/create.js:9:104)
    at new Struct (/home/rkmax/my_project/node_modules/tcomb/lib/struct.js:82:19)
    at Struct (/home/rkmax/my_project/node_modules/tcomb/lib/struct.js:71:14)
    at Object.<anonymous> (/home/rkmax/my_project/date.test.js:10:18)
    at Module._compile (module.js:641:30)
```

**Comment by rkmax** [comment]
reading the docs I found a way
```

t.Date.fromJSON = function(x) {
  return isNaN(Date.parse(x)) ? x : new Date(x);
};
```

and ensure to call fromJSON when fetch data from db

**Comment by StreetStrider** [comment]
@rkmax I got more narrow and explicit case:
```js
tcomb.Date(new Date) // throws
```
However custom `instanceof Date`:
```js
var D = tcomb.irreducible('D', it => it instanceof Date)
D(new Date) // works
```
