### ISSUE TITLE
[Question/Bug] How to use fromJSON and defaultProps

### ISSUE THREAD

**Issue by rkmax** [gcanti/tcomb#312]
### Version

3.2.24

### Expected behaviour

Allow use custom deserialize functions and the defaultProps

### Actual behaviour

the fromJSON function is not using the defaultProps from t.struct

### Steps to reproduce

```js
const t = require('tcomb');
const fromJSON = require('tcomb/lib/fromJSON');

t.Date.fromJSON = function(x) {
  return isNaN(Date.parse(x)) ? x : new Date(x);
};

const Sample = t.struct(
  {
    date: t.Date
  },
  {
    defaultProps: {
      get date() {
        return new Date();
      }
    }
  }
);

const sample = Sample({});
const json = JSON.parse(JSON.stringify(sample));
console.log(fromJSON(json, Sample));
console.log(fromJSON({}, Sample));
```

### Stack trace and console log

```
➔ node date.test.js
Struct { date: 2018-02-22T21:16:17.823Z }
/home/rkmax/my_project/node_modules/tcomb/lib/fail.js:2
  throw new TypeError('[tcomb] ' + message);
  ^

TypeError: [tcomb] Invalid value undefined supplied to Struct{date: Date}/date: Date
    at Function.fail (/home/rkmax/my_project/node_modules/tcomb/lib/fail.js:2:9)
    at assert (/home/rkmax/my_project/node_modules/tcomb/lib/assert.js:14:12)
    at Irreducible (/home/rkmax/my_project/node_modules/tcomb/lib/irreducible.js:18:7)
    at create (/home/rkmax/my_project/node_modules/tcomb/lib/create.js:9:104)
    at fromJSON (/home/rkmax/my_project/node_modules/tcomb/lib/fromJSON.js:26:12)
    at fromJSON (/home/rkmax/my_project/node_modules/tcomb/lib/fromJSON.js:61:20)
    at Object.<anonymous> (/home/rkmax/my_project/date.test.js:25:13)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)

```

**Comment by gcanti** [comment]
@rkmax looks like `fromJSON` ignores `type.meta.defaultProps` here https://github.com/gcanti/tcomb/blob/fbac99fd1da09647fe0b00c124a52c2eafed76ff/lib/fromJSON.js#L61

I guess should be

```js
var actual = value[k];
// apply defaults
if (actual === undefined) {
  actual = type.meta.defaultProps[k];
}
ret[k] = fromJSON(actual, props[k], ( process.env.NODE_ENV !== 'production' ? path.concat(k + ': ' + getTypeName(props[k])) : null ));
```

as I did here https://github.com/gcanti/tcomb/blob/fbac99fd1da09647fe0b00c124a52c2eafed76ff/lib/struct.js#L77

Would you like to send a PR?

**Comment by rkmax** [comment]
For sure!

**Comment by rkmax** [comment]
@gcanti
