### ISSUE TITLE
TypeError: [tcomb] Invalid argument props

### ISSUE THREAD

**Issue by relicmelex** [gcanti/tcomb#319]
### Expected behaviour:
 `t.Struct({...})` should create a new type

### Actual behaviour:
 Throwing a type error

### Steps to reproduce

```
"use strict"
import tcomb from "tcomb"

const ArrayMinLength = tcomb.refinement( tcomb.Array, arr => arr.length >= 0 )
const ArrayMaxLength = tcomb.refinement( tcomb.Array, arr => arr.length < 5 )
const dimensionArray = tcomb.intersection( [ ArrayMinLength, ArrayMaxLength ] )
const DimensionArray = tcomb.refinement( tcomb.Array, arr => dimensionArray.is( arr ), "DimensionArray" )

const OrderType = tcomb.refinement( tcomb.String, str => str.toLowerCase() === "asc" || str.toLowerCase() === "desc", "OrderType" )

const FilterObject = tcomb.struct({
  country: tcomb.String,
  platform: tcomb.String,
  appId: tcomb.String,
  publisherId: tcomb.maybe( tcomb.Number )
}, { name: "FilterObject", strict: true } )

const ContractType = tcomb.struct({
  startDate: tcomb.Number,
  endDate: tcomb.Number,
  dimensions: tcomb.DimensionArray,
  filters: tcomb.FilterObject,
  appId: tcomb.Number,
  country: tcomb.String,
  platform: tcomb.String,
  from: tcomb.Number,
  size: tcomb.Number,
  order: tcomb.OrderType,
  sort: tcomb.String
}, { name: "ContractType" } )
```

```
### Stack trace and console log
    TypeError: [tcomb] Invalid argument props {
|   "startDate": "Number",
|   "endDate": "Number",
|   "appId": "Number",
|   "country": "String",
|   "platform": "String",
|   "from": "Number",
|   "size": "Number",
|   "sort": "String"
| } supplied to struct(props, [options]) combinator (expected a dictionary String -> Type)
|     at Function.fail (/usr/src/app/node_modules/tcomb/lib/fail.js:2:9)
|     at assert (/usr/src/app/node_modules/tcomb/lib/assert.js:14:12)
|     at Function.struct (/usr/src/app/node_modules/tcomb/lib/struct.js:43:5)
|     at Object.<anonymous> (/usr/src/app/dist/Service.js:83:36)
|     at Module._compile (module.js:635:30)
|     at Object.Module._extensions..js (module.js:646:10)
|     at Module.load (module.js:554:32)
|     at tryModuleLoad (module.js:497:12)
|     at Function.Module._load (module.js:489:3)
|     at Module.require (module.js:579:17)
```

Honestly, I'm not sure what I'm doing wrong. I feel like I've done this before, and I swear it almost mimics the samples directly... I hope it's something stupid and I'm not trying to do something anti-pattern or unsupported. ( I feel like just about everything is supported here if you just know how to extend/implement and I've just got to be doing it incorrectly )

**Comment by gcanti** [comment]
```diff
const ContractType = tcomb.struct(
  {
    startDate: tcomb.Number,
    endDate: tcomb.Number,
-    dimensions: tcomb.DimensionArray,
+    dimensions: DimensionArray,
-    filters: tcomb.FilterObject,
+    filters: FilterObject,
    appId: tcomb.Number,
    country: tcomb.String,
    platform: tcomb.String,
    from: tcomb.Number,
    size: tcomb.Number,
-    order: tcomb.OrderType,
+    order: OrderType,
    sort: tcomb.String
  },
  { name: 'ContractType' }
)
```

**Comment by relicmelex** [comment]
@gcanti 

This is what I meant by anti-pattern. I feel like this is breaking the standard that is set in the example:

```
const Integer = t.refinement(t.Number, (n) => n % 1 === 0, 'Integer');
```

```
const Person = t.struct({
  name: t.String,              // required string
  surname: t.maybe(t.String),  // optional string
  age: t.Integer,                // required integer
  tags: t.list(t.String)       // a list of strings
}, 'Person');
```

Instead of just pasting a block of code can you do me the courtesy of explaining what's going on here and why it's documented one way and only works another? Or am I still missing something?

**Comment by gcanti** [comment]
@relicmelex I'm sorry, I thought that the fix was clear. 

Explanation: `DimensionArray`, `FilterObject` and `OrderType` are define by you, so they can't be found in the `tcomb` namespace (as opposed to `tcomb.Number`, `tcomb.String` or `tcomb.Integer`). If you just remove the `tcomb.` prefix everything works fine.

**Comment by relicmelex** [comment]
@gcanti I must have been unclear. I can tell that that's what you've done.

I want to know how to add it to the tcomb namespace like the example so I can have one form of code in one place and another in a different. This is a mixed pattern and in the example it shows that you can extend the tcomb namespace and I figured that's what the "name" opttion was for in the first place. Correct me if I'm wrong or else that option is completely useless?
